apiVersion: batch/v1
kind: Job
metadata:
  name: cadence-schema-setup
  labels:
    {{- include "cadence.commonlabels" . | nindent 4 }}
spec:
  backoffLimit: 4
  template:
    metadata:
      name: cadence-schema-setup
    spec:
      restartPolicy: "OnFailure"
      initContainers:
        # Check Cassandra DNS resolution using busybox
        - name: check-cassandra-dns
          image: busybox
          command: ['sh', '-c', '
            until nslookup  {{ include "cassandra.endpoint" . }}; do
              echo "Waiting for Cassandra service DNS resolution...";
              sleep 5;
            done;
            echo "Cassandra service DNS resolved.";
          ']
        # Check Cassandra readiness using cqlsh
        - name: check-cassandra-ready
          image: {{ .Values.history.image.repository }}:{{ .Values.history.image.tag }}
          imagePullPolicy: Always
          command: ['sh', '-c', '
            until cqlsh {{ include "cassandra.endpoint" . }} 9042 -e "SHOW VERSION"; do
              echo "Waiting for Cassandra to start...";
              sleep 30;
            done;
            echo "Cassandra is up and running.";
          ']
      containers:
        - name: schema-setup
          image: {{ .Values.history.image.repository }}:{{ .Values.history.image.tag }}
          imagePullPolicy: Always
          env:
            - name: CASSANDRA_SEEDS
              value:  {{ include "cassandra.endpoint" . }}
            - name: KEYSPACE
              value: cadence
            - name: VISIBILITY_KEYSPACE
              value: cadence_visibility
            - name: RF
              value: "1"
            - name: CADENCE_HOME
              value: /etc/cadence
          args: ['sh', '-c', '
            SCHEMA_DIR=$CADENCE_HOME/schema/cassandra/cadence/versioned;
            cadence-cassandra-tool --ep $CASSANDRA_SEEDS create -k $KEYSPACE --rf $RF;
            cadence-cassandra-tool --ep $CASSANDRA_SEEDS -k $KEYSPACE setup-schema -v 0.0;
            cadence-cassandra-tool --ep $CASSANDRA_SEEDS -k $KEYSPACE update-schema -d $SCHEMA_DIR;

            VISIBILITY_SCHEMA_DIR=$CADENCE_HOME/schema/cassandra/visibility/versioned;
            cadence-cassandra-tool --ep $CASSANDRA_SEEDS create -k $VISIBILITY_KEYSPACE --rf $RF;
            cadence-cassandra-tool --ep $CASSANDRA_SEEDS -k $VISIBILITY_KEYSPACE setup-schema -v 0.0;
            cadence-cassandra-tool --ep $CASSANDRA_SEEDS -k $VISIBILITY_KEYSPACE update-schema -d $VISIBILITY_SCHEMA_DIR;
          ']
