apiVersion: v1
kind: ConfigMap
metadata:
  name: cadence-configmap
  labels:
    {{- include "cadence.commonlabels" . | nindent 4 }}
data:
  dynamic_config.yaml: |-
    {{- toYaml .Values.dynamicConfig.values | nindent 12 }}
